# Generated by Django 5.0.2 on 2024-02-13 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cohort'),
        ),
        migrations.AddField(
            model_name='classattendance',
            name='class_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classschedule'),
        ),
        migrations.AddField(
            model_name='query',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querycomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querycomment',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.query'),
        ),
    ]
